# Generated by Django 4.0.3 on 2022-04-29 16:53

import car_cost_tracker.helpers.models_helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), car_cost_tracker.helpers.models_helpers.only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), car_cost_tracker.helpers.models_helpers.only_letters]),
        ),
    ]
