# Generated by Django 4.0.3 on 2022-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
