# Generated by Django 4.0.3 on 2022-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='car',
            field=models.CharField(choices=[], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
